### ISSUE TITLE
Subtask Report 4: ADD

### ISSUE THREAD

**Issue by thongdanghoang** [thongdanghoang/greenbuildings#19]
DoD: 
- [x] use cases diagram
- [ ] Business information model + most important entities and their relationships
- [x] The technologies used in the layers (=Tiers)
- [x] GreenBuildings and partner components
- [x] The internal components of GreenBuildings at a glance
- [ ] The service components and their responsibilities for specific use cases
- [ ] The service components and their responsibilities for business entities
- [x] Each service component has its own database schema
- [x] Service components operate in an Azure environment.
- [x] The Azure objects and the GreenBuildings micro services
- [x] The interactions when a registered user logs in.
